### ISSUE TITLE
Question: Proposed solution for python2 missing from macOS 12.3+ 

### ISSUE THREAD

**Issue by noaht8um** [johnduprey/CWCAutomateDiagnostics#12]
macOS doesn't include python anymore. I am almost done with a shell script that replicates everything the python script does for macs. Is this something that would be possible to integrate as its own thing i.e. AutomateDiagnostics.sh? If so, I can submit a PR once I finish figuring out the lterrors piece.

**Comment by dracoyinyang** [comment]
As I have noticed I am getting this error on macs.

DIAGNOSTIC-RESPONSE/1
DiagnosticType: Automate
ContentType: json
sh: line 3: python: command not found

I do maintain a lot of mac systems as well as windows.  I love the use of this tool since Connectwise basically makes nothing that works quite as well as this.  I would appreciate any help.

**Comment by JohnDuprey** [comment]
Fixed in #15, changes submitted to CW Control marketplace for review
