### ISSUE TITLE
Plugin Crashes Control Host Services on 22.9.10446.8359

### ISSUE THREAD

**Issue by TimBloom** [johnduprey/CWCAutomateDiagnostics#13]
We recently upgraded Control to 22.9.10446.8359, but after upgrading Control would not respond after 10-20 minutes of uptime. We narrowed the issue down to this plugin, and since disabling we have functioned normally.

**Comment by JohnDuprey** [comment]
There is a known issue with the Session Event Trigger slowing things down after updates due to lots of agent disconnect/connect events. It's recommended to set Maintenance mode to 1 in the extension settings before performing updates. 

https://github.com/johnduprey/CWCAutomateDiagnostics/blob/e3b22e33c671b3acf0cc09897e52defc5097708b/Manifest.xml#L38-L41
